language: haskell
ghc:
    - 7.8
    - 7.6
install:
    - "cabal install --only-dependencies"
script:
    - "cabal configure --enable-tests && cabal build && cabal test"
notifications:
    email: true

